# Generated by Django 3.1.2 on 2021-09-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20210927_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='participant',
            new_name='participants',
        ),
    ]
